// Warning: generated file; your changes could be lost when a new file is generated.
#I __SOURCE_DIRECTORY__
#load "load-references-debug.fsx"
#load "../AssemblyInfo.fs"
      "../CommonTypes.fs"
      "../TalkTable.fs"
      "../ArchiveFiles.fs"
      "../SerializedGFF.fs"
      "../GFF.fs"
      "../GFFFileTypes.fs"
      "../IAResourceManager.fs"
      "../TwoDA.fs"
      "../NWN1Context.fs"
      "../JadeEmpireContext.fs"
      "../KOTOR1Context.fs"
      "../AuroraPlugin.fs"
