// Warning: generated file; your changes could be lost when a new file is generated.
#I __SOURCE_DIRECTORY__
#load "load-references-debug.fsx"
#load "../../../paket-files/enovales/SegaAFSTools/src/SegaAFSTools/AFS.fs"
      "../AssemblyInfo.fs"
      "../Utils.fs"
      "../Data.fs"
      "../XUIGames.fs"
      "../JetSetRadio.fs"
      "../SpaceChannel5.fs"
      "../Magicka.fs"
      "../WormsArmageddon.fs"
      "../PuzzleQuestGames.fs"
      "../PillarsOfEternity.fs"
      "../OrcsMustDie.fs"
      "../MadballsBaboInvasion.fs"
      "../CivilizationGames.fs"
      "../ParadoxStrategyGames.fs"
      "../AgeOfEmpiresGames.fs"
      "../SimpleGames.fs"
      "../OneOffGamesPlugin.fs"
      "../AssemblyInfoStatic.fs"
