// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("LLsqlite-net")]
[assembly: AssemblyProductAttribute("LudumLinguarum")]
[assembly: AssemblyDescriptionAttribute("Tools for extracting localized content from games, and turning them into language learning content.")]
[assembly: AssemblyVersionAttribute("0.10.0")]
[assembly: AssemblyFileVersionAttribute("0.10.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.10.0";
        internal const string InformationalVersion = "0.10.0";
    }
}
