// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("LLsqlite-net")]
[assembly: AssemblyProductAttribute("LudumLinguarum")]
[assembly: AssemblyDescriptionAttribute("Tools for extracting localized content from games, and turning them into language learning content.")]
[assembly: AssemblyVersionAttribute("0.17.2")]
[assembly: AssemblyFileVersionAttribute("0.17.2")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "LLsqlite-net";
        internal const System.String AssemblyProduct = "LudumLinguarum";
        internal const System.String AssemblyDescription = "Tools for extracting localized content from games, and turning them into language learning content.";
        internal const System.String AssemblyVersion = "0.17.2";
        internal const System.String AssemblyFileVersion = "0.17.2";
    }
}
