// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("PInvokeStubs")]
[assembly: AssemblyProductAttribute("LudumLinguarum")]
[assembly: AssemblyDescriptionAttribute("Tools for extracting localized content from games, and turning them into language learning content.")]
[assembly: AssemblyVersionAttribute("1.0.1")]
[assembly: AssemblyFileVersionAttribute("1.0.1")]
[assembly: AssemblyConfigurationAttribute("Release")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "PInvokeStubs";
        internal const System.String AssemblyProduct = "LudumLinguarum";
        internal const System.String AssemblyDescription = "Tools for extracting localized content from games, and turning them into language learning content.";
        internal const System.String AssemblyVersion = "1.0.1";
        internal const System.String AssemblyFileVersion = "1.0.1";
        internal const System.String AssemblyConfiguration = "Release";
    }
}
