name: Build master

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK from global.json
      uses: actions/setup-dotnet@v1.7.2

    - name: Build
      if: runner.os != 'Windows'
      run: |
        chmod +x ./build.sh
        ./build.sh
      env:
        CI: true
    - name: Build
      if: runner.os == 'Windows'
      run: ./build.cmd
      env:
        CI: true
